server:
  port: 9001
  servlet:
    context-path: /api
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: admin
#    driver-class-name: com.mysql.jdbc.Driver
    #动态数据源
    dynamic:
      master:
        jdbc-url: jdbc:mysql://localhost:3306/sharp_sword?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root123456
        driver-class-name: com.mysql.jdbc.Driver
        pool-name: Master-DB
#      slave1:
#        jdbc-url: jdbc:mysql://192.168.152.128:3306/sharp_sword?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.jdbc.Driver
#        pool-name: Slave1-DB
  redis:
    host: 192.168.152.129
    port: 6379
#    password: redis123

#定时任务相关
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.simpl.RAMJobStore
    # cronMap 和 details 同时配置 cronMap 优先
    cronMap:
      com_jamie_framework_quartz_job_OpLogWriteQuartzJob: 0/30 * * * * ? *
    details:
      com_jamie_framework_quartz_job_OpLogWriteQuartzJob: # QuartzCronProperties 注入时候 "." 分割无法注入(null)，所以使用"_" 下划线隔开包名
        interval: 1
        repeatCount: 3
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.74.131:9200
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: mail.test.com
    username: test1
#    password: test1
    port: 25
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  # freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
logging:
  level:
    com.jamie.framework: info
  path: D:\logs
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-handlers-package: com.jamie.framework.mybatis.handler
  global-config:
    banner: false
  type-aliases-package: com.jamie.framework.mybatis.handler
# 系统配置
app:
  key: APP1
  login-salt-timeout-seconds: 60
  exclude-urls: /instances,/actuator/**,/search/**,/test/**
#登录验证相关
login:
  validator:
    captcha: true
    verifyPasswordErrorNum: true
shiro:
  jwt:
    tokenName: X-TOKEN
    secret: 123456
    issuer: lz
    subject: test
    expire-second: 3600
    refresh-token-interval: 60 #值越小，刷新率越高；当前时间 + (超时时间 - 刷新时间) > 过期时间(未来某个时间点) 则刷新token
    single-login: true
zookeeper:
  connect-addr: 192.168.74.128:2181
  namespace: super

# xxl-job -------------------------start
### actuator
management:
  context-path: /actuator
  health:
    mail:
      enabled: false
xxl:
  job:
    ## 调度中心通讯TOKEN
    accessToken:
    ## 调度中心国际化配置
    i18n:
    logretentiondays: 30
    ## 调度线程池最大线程配置
    triggerpool:
      fast:
        max: 10
      slow:
        max: 5
    # 执行器端（业务模块端配置）
    client:
      # 调度中心部署跟地址，如果是外部服务则配置xxl-job服务器地址
      admin-addresses: http://127.0.0.1:${server.port}${server.servlet.context-path}/xxl-job-admin
      # 执行器AppName
      appName: xxl-job-executor
      # 执行器IP
      ip:
      # 执行器端口号,xxl服务器与业务模块rpc通信端口,不能与业务模块服务端口相同
      port: 9091
      ## 执行器通讯TOKEN
      access-token:
      ## 执行器运行日志文件存储磁盘路径
      log-path:
      ## 执行器日志文件保存天数
      log-retention-days: 30

# xxl-job -------------------------end
